# Generated by Django 6.0.4 on 2026-04-25 22:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('ordem_parada', models.IntegerField()),
            ],
            options={
                'ordering': ['ordem_parada'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('cor', models.CharField(blank=True, max_length=30, null=True)),
                ('ano', models.IntegerField()),
                ('id_proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('vagas_totais', models.IntegerField()),
                ('status_viagem', models.CharField(choices=[('Aberta', 'Aberta'), ('Em Curso', 'Em Curso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Aberta', max_length=15)),
                ('id_motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_dirigidas', to=settings.AUTH_USER_MODEL)),
                ('id_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caronas.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_bagagem', models.IntegerField(default=0)),
                ('status_solicitacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Aceita', 'Aceita'), ('Recusada', 'Recusada')], default='Pendente', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('id_parada_desembarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desembarques', to='caronas.parada')),
                ('id_parada_embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='caronas.parada')),
                ('id_passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_reservas', to=settings.AUTH_USER_MODEL)),
                ('id_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='caronas.viagem')),
            ],
        ),
        migrations.AddField(
            model_name='parada',
            name='id_viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='caronas.viagem'),
        ),
    ]
